// This code was autogenerated from natsrpc.gencode, do not edit.
package pb

import (
	"context"

	"github.com/byebyebruce/natsrpc"
	"github.com/golang/protobuf/proto"
	"github.com/nats-io/nats.go"
)

var _ proto.Message

// Greeter
type Greeter interface {
	// AreYouOK
	AreYouOK(ctx context.Context, req *HelloRequest) (*HelloReply, error)
	// TTAAsync
	TTAAsync(ctx context.Context, req *TTRequest, cb func(*TTReply, error))
	// TTA2Async
	TTA2Async(ctx context.Context, req *TTRequest, cb func(*TTReply, error))
	// PublishTTP
	PublishTTP(ctx context.Context, notify *TTRequest) error
}

// RegisterGreeter
func RegisterGreeter(server *natsrpc.Server, s Greeter, opts ...natsrpc.Option) (natsrpc.Service, error) {
	return server.Register("github.com/byebyebruce/natsrpc/testdata/pb.Greeter", s, opts...)
}

// GreeterClient
type GreeterClient struct {
	c *natsrpc.Client
}

// NewGreeterClient
func NewGreeterClient(enc *nats.EncodedConn, opts ...natsrpc.Option) (*GreeterClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com/byebyebruce/natsrpc/testdata/pb.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &GreeterClient{
		c: c,
	}
	return ret, nil
}

// ID 根据ID获得client
func (c *GreeterClient) ID(id interface{}) *GreeterClient {
	return &GreeterClient{
		c: c.c.ID(id),
	}
}

// AreYouOK
func (c *GreeterClient) AreYouOK(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	rep := &HelloReply{}
	err := c.c.Request(ctx, "AreYouOK", req, rep)
	return rep, err
}

// TTAAsync
func (c *GreeterClient) TTAAsync(ctx context.Context, req *TTRequest, cb func(*TTReply, error)) {
	rep := &TTReply{}
	f := func(_ proto.Message, err error) {
		cb(rep, err)
	}
	c.c.AsyncRequest("TTA", req, rep, f)
}

// TTA2Async
func (c *GreeterClient) TTA2Async(ctx context.Context, req *TTRequest, cb func(*TTReply, error)) {
	rep := &TTReply{}
	f := func(_ proto.Message, err error) {
		cb(rep, err)
	}
	c.c.AsyncRequest("TTA2", req, rep, f)
}

// PublishTTP
func (c *GreeterClient) PublishTTP(ctx context.Context, notify *TTRequest) error {
	return c.c.Publish("TTP", notify)
}
