// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natsrpc.proto

package natsrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//message request {
//bytes data = 1;
//map<string,string> header = 2; // 目前没用，等后面nats.go更新到新版本直接用内置的header
//}
type Reply struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{0}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Reply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Int32 struct {
	Val                  int32    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{2}
}

func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (m *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(m, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

type String struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{3}
}

func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

var E_ServiceAsync = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         43230,
	Name:          "natsrpc.serviceAsync",
	Tag:           "varint,43230,opt,name=serviceAsync",
	Filename:      "natsrpc.proto",
}

var E_ClientAsync = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         43231,
	Name:          "natsrpc.clientAsync",
	Tag:           "varint,43231,opt,name=clientAsync",
	Filename:      "natsrpc.proto",
}

var E_Publish = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         2360,
	Name:          "natsrpc.publish",
	Tag:           "varint,2360,opt,name=publish",
	Filename:      "natsrpc.proto",
}

func init() {
	proto.RegisterType((*Reply)(nil), "natsrpc.reply")
	proto.RegisterType((*Empty)(nil), "natsrpc.Empty")
	proto.RegisterType((*Int32)(nil), "natsrpc.Int32")
	proto.RegisterType((*String)(nil), "natsrpc.String")
	proto.RegisterExtension(E_ServiceAsync)
	proto.RegisterExtension(E_ClientAsync)
	proto.RegisterExtension(E_Publish)
}

func init() {
	proto.RegisterFile("natsrpc.proto", fileDescriptor_210d289958f39804)
}

var fileDescriptor_210d289958f39804 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xda, 0xad, 0x1b, 0x57, 0x90, 0xe0, 0xa1, 0xee, 0x41, 0x4b, 0x0f, 0xd2, 0x53,
	0x8b, 0xee, 0xc9, 0x7a, 0x52, 0xd9, 0x83, 0x07, 0x11, 0xba, 0x37, 0x6f, 0x6d, 0x1a, 0xdb, 0x40,
	0x37, 0x09, 0x93, 0xe9, 0x42, 0xdf, 0xcc, 0xd7, 0xf0, 0x05, 0xf4, 0x55, 0xa4, 0x69, 0x0b, 0x2b,
	0x5e, 0x84, 0x40, 0x66, 0xf2, 0xcf, 0xf7, 0xe7, 0x67, 0xc8, 0xa9, 0xcc, 0xd1, 0x80, 0x66, 0xb1,
	0x06, 0x85, 0x8a, 0x7a, 0x63, 0xbb, 0x0c, 0x2a, 0xa5, 0xaa, 0x86, 0x27, 0xf6, 0xb9, 0x68, 0xdf,
	0x93, 0x92, 0x1b, 0x06, 0x42, 0xa3, 0x82, 0x61, 0x34, 0xbc, 0x21, 0x2e, 0x70, 0xdd, 0x74, 0x94,
	0x92, 0xa3, 0x32, 0xc7, 0xdc, 0x77, 0x02, 0x27, 0x5a, 0x64, 0xb6, 0xa6, 0xe7, 0xc4, 0xe5, 0x00,
	0x0a, 0xfc, 0x83, 0xc0, 0x89, 0xe6, 0xd9, 0xd0, 0x84, 0x1e, 0x71, 0xd7, 0x5b, 0x8d, 0x5d, 0x78,
	0x41, 0xdc, 0x67, 0x89, 0xab, 0x5b, 0x7a, 0x46, 0x0e, 0x77, 0x79, 0x63, 0x51, 0x37, 0xeb, 0xcb,
	0x70, 0x49, 0x66, 0x1b, 0x04, 0x21, 0xab, 0x7d, 0x6d, 0x6e, 0xb5, 0x74, 0x4d, 0x16, 0x86, 0xc3,
	0x4e, 0x30, 0xfe, 0x60, 0x3a, 0xc9, 0xe8, 0x55, 0x3c, 0xa4, 0x8c, 0xa7, 0x94, 0xf1, 0x66, 0x90,
	0x5f, 0x35, 0x0a, 0x25, 0x8d, 0xff, 0xf5, 0xd9, 0xff, 0x7f, 0x9c, 0xfd, 0xc2, 0xd2, 0x27, 0x72,
	0xc2, 0x1a, 0xc1, 0x25, 0xfe, 0xd3, 0xe5, 0x7b, 0x74, 0xd9, 0xa7, 0xd2, 0x3b, 0xe2, 0xe9, 0xb6,
	0x68, 0x84, 0xa9, 0xe9, 0xe5, 0x1f, 0x83, 0x17, 0x8e, 0xb5, 0x2a, 0x27, 0xfe, 0x83, 0x5a, 0x7c,
	0x9a, 0x7f, 0x8c, 0xde, 0xae, 0x2b, 0x81, 0x75, 0x5b, 0xc4, 0x4c, 0x6d, 0x93, 0xa2, 0xe3, 0xfd,
	0x81, 0x96, 0xf1, 0x64, 0xdc, 0xfe, 0xfd, 0x78, 0x17, 0x33, 0xeb, 0xb8, 0xfa, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x20, 0x45, 0xc8, 0x03, 0xa6, 0x01, 0x00, 0x00,
}
