// Code generated by protoc-gen-go. DO NOT EDIT.
// source: natsrpc.proto

package natsrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MethodType int32

const (
	MethodType_A MethodType = 0
	MethodType_S MethodType = 1
	MethodType_P MethodType = 2
)

var MethodType_name = map[int32]string{
	0: "A",
	1: "S",
	2: "P",
}

var MethodType_value = map[string]int32{
	"A": 0,
	"S": 1,
	"P": 2,
}

func (x MethodType) String() string {
	return proto.EnumName(MethodType_name, int32(x))
}

func (MethodType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_210d289958f39804, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

var E_MethodType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*MethodType)(nil),
	Field:         2360,
	Name:          "annotation.methodType",
	Tag:           "varint,2360,opt,name=methodType,enum=annotation.MethodType",
	Filename:      "natsrpc.proto",
}

func init() {
	proto.RegisterEnum("annotation.MethodType", MethodType_name, MethodType_value)
	proto.RegisterType((*Empty)(nil), "annotation.Empty")
	proto.RegisterExtension(E_MethodType)
}

func init() {
	proto.RegisterFile("natsrpc.proto", fileDescriptor_210d289958f39804)
}

var fileDescriptor_210d289958f39804 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0x2c, 0x29,
	0x2e, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xcc, 0xcb, 0xcb, 0x2f,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x93, 0x52, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xcb,
	0x24, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16, 0x94, 0xe4, 0x17, 0x41, 0x54,
	0x2b, 0xb1, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x6a, 0x29, 0x72, 0x71, 0xf9, 0xa6, 0x96,
	0x64, 0xe4, 0xa7, 0x84, 0x54, 0x16, 0xa4, 0x0a, 0xb1, 0x72, 0x31, 0x3a, 0x0a, 0x30, 0x80, 0xa8,
	0x60, 0x01, 0x46, 0x10, 0x15, 0x20, 0xc0, 0x64, 0x15, 0xce, 0xc5, 0x95, 0x8b, 0x50, 0x22, 0xa7,
	0x07, 0x31, 0x5c, 0x0f, 0x66, 0xb8, 0x1e, 0x44, 0xbf, 0x7f, 0x01, 0xc8, 0xea, 0x62, 0x89, 0x1d,
	0x42, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x62, 0x7a, 0x08, 0xf7, 0xe8, 0x21, 0x6c, 0x08, 0x42, 0x32,
	0xca, 0x89, 0x33, 0x8a, 0x1d, 0xea, 0x87, 0x24, 0x36, 0xb0, 0x69, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xab, 0xa8, 0x27, 0x0f, 0xd5, 0x00, 0x00, 0x00,
}
