package main

import (
	"fmt"
	"strings"

	"github.com/byebyebruce/natsrpc"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPackage = protogen.GoImportPath("context")
	natsrpcPackage = protogen.GoImportPath("github.com/byebyebruce/natsrpc")
)

// generateFile generates .natsrpc.pb.go file
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	if len(file.Services) == 0 {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_natsrpc.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-natsrpc. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-natsrpc %s", natsrpc.Version))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g)
	return g
}

// generateFileContent generates
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	if len(file.Services) == 0 {
		return
	}
	g.P("var _ ", contextPackage.Ident("Context"))
	supportVersionVar := "SupportVersion_" + strings.ReplaceAll(strings.TrimPrefix(natsrpc.Version, "v"), ".", "_")
	g.P("var _ = ", natsrpcPackage.Ident(supportVersionVar))

	g.P()

	fd := fileSpec{
		Services: make([]*serviceDesc, 0),
	}
	for _, service := range file.Services {
		sd := genService(g, service, file.Desc.Path())
		fd.Services = append(fd.Services, sd)
	}
	g.P(fd.execute())
}

func genService(g *protogen.GeneratedFile, service *protogen.Service, metadata string) *serviceDesc {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	sd := &serviceDesc{
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Comment:     service.Comments.Leading.String(),
		Metadata:    metadata,
	}
	for _, method := range service.Methods {
		sd.Methods = append(sd.Methods, buildMethodDesc(g, method))
	}
	return sd
}

func buildMethodDesc(g *protogen.GeneratedFile, m *protogen.Method) *methodDesc {
	ms := &methodDesc{
		Name:         m.GoName,
		OriginalName: string(m.Desc.Name()),
		Request:      g.QualifiedGoIdent(m.Input.GoIdent),
		Reply:        g.QualifiedGoIdent(m.Output.GoIdent),
		Comment:      m.Comments.Leading.String(),
	}
	if v, ok := proto.GetExtension(m.Desc.Options(), natsrpc.E_Publish).(bool); ok {
		ms.Publish = v
	}
	return ms
}

const deprecationComment = "// Deprecated: Do not use."
