// This code was autogenerated from natsrpc.gencode, do not edit.

package service

import (
	"context"
	"github.com/byebyebruce/natsrpc//Users/bruce/Documents/proj/natsrpc/example/../example/api"
	"github.com/byebyebruce/natsrpc/testdata"

	"github.com/byebyebruce/natsrpc"
)

// RegisterExampleService
func RegisterExampleService(server *natsrpc.Server, s api.ExampleService, opts ...natsrpc.Option) (natsrpc.Service, error) {
	return server.Register(s, opts...)
}

// RegisterHelloService
func RegisterHelloService(server *natsrpc.Server, s api.HelloService, opts ...natsrpc.Option) (natsrpc.Service, error) {
	return server.Register(s, opts...)
}

// ExampleServiceServer is the interface that providers of the service
// ExampleService should implement.
type ExampleServiceServer interface {
	Notify(ctx context.Context, req helloworld.HelloReply)
	Request(ctx context.Context, req helloworld.HelloRequest, repl helloworld.HelloReply)
}

// HelloServiceServer is the interface that providers of the service
// HelloService should implement.
type HelloServiceServer interface {
	Notify(ctx context.Context, req helloworld.HelloReply)
	Request(ctx context.Context, req helloworld.HelloRequest, repl helloworld.HelloReply)
}
