// Code generated by protoc-gen-natsrpc. DO NOT EDIT.
// versions:
// - protoc-gen-natsrpc v0.5.0
// source: async_client.proto

package async_client

import (
	context "context"
	fmt "fmt"
	natsrpc "github.com/byebyebruce/natsrpc"
	testdata "github.com/byebyebruce/natsrpc/testdata"
	nats_go "github.com/nats-io/nats.go"
	proto "google.golang.org/protobuf/proto"
)

var _ = new(context.Context)
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = natsrpc.Version
var _ = nats_go.Version

type GreeterNATSRPCServer interface {
	Hello(ctx context.Context, req *testdata.HelloRequest) (*testdata.HelloReply, error)
	HelloToAll(ctx context.Context, req *testdata.HelloRequest)
}

// RegisterGreeterNATSRPCServer register Greeter service
func RegisterGreeterNATSRPCServer(server *natsrpc.Server, s GreeterNATSRPCServer, opts ...natsrpc.ServiceOption) (natsrpc.IService, error) {
	return server.Register("github.com.byebyebruce.natsrpc.example.pb.async_client.Greeter", s, opts...)
}

type GreeterNATSRPCClient interface {
	Hello(ctx context.Context, req *testdata.HelloRequest, opt ...natsrpc.CallOption) (*testdata.HelloReply, error)
	HelloToAll(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error
}

type _GreeterNATSRPCClient struct {
	c *natsrpc.Client
}

// NewGreeterNATSRPCClient
func NewGreeterNATSRPCClient(enc *nats_go.EncodedConn, opts ...natsrpc.ClientOption) (GreeterNATSRPCClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com.byebyebruce.natsrpc.example.pb.async_client.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &_GreeterNATSRPCClient{
		c: c,
	}
	return ret, nil
}
func (c *_GreeterNATSRPCClient) Hello(ctx context.Context, req *testdata.HelloRequest, opt ...natsrpc.CallOption) (*testdata.HelloReply, error) {
	rep := &testdata.HelloReply{}
	err := c.c.Request(ctx, "Hello", req, rep, opt...)
	return rep, err
}
func (c *_GreeterNATSRPCClient) HelloToAll(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error {
	return c.c.Publish("HelloToAll", notify, opt...)
}

// Async
// GreeterAsyncClient
type GreeterAsyncClient interface {
	Hello(ctx context.Context, req *testdata.HelloRequest, cb func(*testdata.HelloReply, error), opt ...natsrpc.CallOption)
	HelloToAll(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error
}

type _GreeterAsyncNATSRPCClient struct {
	c    *natsrpc.Client
	doer natsrpc.AsyncDoer
}

// NewGreeterAsyncClient
func NewGreeterAsyncClient(enc *nats_go.EncodedConn, doer natsrpc.AsyncDoer, opts ...natsrpc.ClientOption) (GreeterAsyncClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com.byebyebruce.natsrpc.example.pb.async_client.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &_GreeterAsyncNATSRPCClient{
		c:    c,
		doer: doer,
	}
	return ret, nil
}
func (c *_GreeterAsyncNATSRPCClient) Hello(ctx context.Context, req *testdata.HelloRequest, cb func(*testdata.HelloReply, error), opt ...natsrpc.CallOption) {
	reqClone := proto.Clone(req)
	go func() {
		rep := &testdata.HelloReply{}
		err := c.c.Request(ctx, "Hello", reqClone, rep, opt...)
		newCb := func(_ func(interface{}, error)) {
			cb(rep, err)
		}
		c.doer.AsyncDo(ctx, newCb)
	}()
}
func (c *_GreeterAsyncNATSRPCClient) HelloToAll(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error {
	return c.c.Publish("HelloToAll", notify, opt...)
}
