// Code generated by protoc-gen-natsrpc. DO NOT EDIT.
package request

import (
	"context"

	"github.com/byebyebruce/natsrpc"
	"github.com/golang/protobuf/proto"
	"github.com/nats-io/nats.go"
)

var _ proto.Message

// Greeter
type Greeter interface { // Hello
	Hello(ctx context.Context, req *HelloRequest) (*HelloReply, error) // ToAll
	ToAll(ctx context.Context, req *Empty)
}

// RegisterGreeter
func RegisterGreeter(server *natsrpc.Server, s Greeter, opts ...natsrpc.ServiceOption) (natsrpc.IService, error) {
	return server.Register("github.com/byebyebruce/example/request.Greeter", s, opts...)
}

// GreeterClient
type GreeterClient struct {
	c *natsrpc.Client
}

// NewGreeterClient
func NewGreeterClient(enc *nats.EncodedConn, opts ...natsrpc.ClientOption) (*GreeterClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com/byebyebruce/example/request.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &GreeterClient{
		c: c,
	}
	return ret, nil
}
