package main
const tFile = `// This code was autogenerated from natsrpc.gencode, do not edit.

package {{.OutPackage}}

import (
	"context"


	{{- range  .Imports}}
	{{.}}
	{{- end}}

	"github.com/byebyebruce/natsrpc"
)
{{- range .Service}}

// Register{{.Name}} 
func Register{{.Name}}(server *natsrpc.Server, s {{$.Package}}.{{.Name}}, opts ...natsrpc.Option) (natsrpc.Service, error) {
	return server.Register(s, opts...)
}
{{- end}}


{{- range .Service}}

// {{.Name}}Server is the interface that providers of the service
// {{.Name}} should implement.
type {{.Name}}Server interface {
	{{- range .Method}}
	{{.Name}}(
		{{- range $i, $v := .Param -}}
			{{- if ne $i 0 -}}
			, 
			{{- end -}}
			{{ $v.Name }} {{ $v.Type }}
		{{- end -}}
	)
	{{- end}}
}
{{- end}}
`
