// Code generated by protoc-gen-natsrpc. DO NOT EDIT.
// source: request.proto

package request

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	nats "github.com/nats-io/nats.go"
	natsrpc "gitlab.uuzu.com/sanguox/natsrpc"
	pb "gitlab.uuzu.com/sanguox/natsrpc/example/pb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// GreeterInterface
type GreeterInterface interface {
	// Hello
	Hello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloReply, error)
}

// RegisterGreeter
func RegisterGreeter(server *natsrpc.Server, s GreeterInterface, opts ...natsrpc.ServiceOption) (natsrpc.IService, error) {
	return server.Register("gitlab.uuzu.com.sanguox.natsrpc.example.pb.request.Greeter", s, opts...)
}

// GreeterClient
type GreeterClient interface {
	// Hello
	Hello(ctx context.Context, req *pb.HelloRequest, opt ...natsrpc.CallOption) (*pb.HelloReply, error)
}
type _GreeterClient struct {
	c *natsrpc.Client
}

// NewGreeterClient
func NewGreeterClient(enc *nats.EncodedConn, opts ...natsrpc.ClientOption) (GreeterClient, error) {
	c, err := natsrpc.NewClient(enc, "gitlab.uuzu.com.sanguox.natsrpc.example.pb.request.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &_GreeterClient{
		c: c,
	}
	return ret, nil
}
func (c *_GreeterClient) Hello(ctx context.Context, req *pb.HelloRequest, opt ...natsrpc.CallOption) (*pb.HelloReply, error) {
	rep := &pb.HelloReply{}
	err := c.c.Request(ctx, "Hello", req, rep, opt...)
	return rep, err
}
