// Code generated by protoc-gen-natsrpc DO NOT EDIT.
// source: async_service.proto

package async_service

import (
	context "context"
	fmt "fmt"
	natsrpc "github.com/byebyebruce/natsrpc"
	pb "github.com/byebyebruce/natsrpc/example/pb"
	proto "github.com/golang/protobuf/proto"
	nats "github.com/nats-io/nats.go"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Greeter
type Greeter interface {
	// Hello
	Hello(ctx context.Context, req *pb.HelloRequest, cb func(*pb.HelloReply, error))
	// HelloToAll
	HelloToAll(ctx context.Context, req *pb.HelloRequest)
}

// RegisterGreeter
func RegisterGreeter(server *natsrpc.Server, s Greeter, doer natsrpc.AsyncDoer, opts ...natsrpc.ServiceOption) (natsrpc.IService, error) {
	ss := &GreeterWrapper{
		doer: doer,
		s:    s,
	}
	return server.Register("github.com.byebyebruce.example.pb.async_service.Greeter", ss, opts...)
}

// GreeterWrapper DO NOT USE
type GreeterWrapper struct {
	doer natsrpc.AsyncDoer
	s    Greeter
}

// Hello DO NOT USE
func (s *GreeterWrapper) Hello(ctx context.Context, req *pb.HelloRequest) (rep *pb.HelloReply, err error) {
	done := make(chan struct{})
	s.doer.Do(ctx, func() {
		cb := func(r *pb.HelloReply, e error) {
			rep, err = r, e
			select {
			case done <- struct{}{}:
			default:
			}
		}
		s.s.Hello(ctx, req, cb)
	})
	select {
	case <-ctx.Done():
		rep, err = nil, ctx.Err()
	case <-done:
	}
	return
}

// HelloToAll DO NOT USE
func (s *GreeterWrapper) HelloToAll(ctx context.Context, req *pb.HelloRequest) {
	s.doer.Do(ctx, func() {
		s.s.HelloToAll(ctx, req)
	})
}

// GreeterClient
type GreeterClient struct {
	c *natsrpc.Client
}

// NewGreeterClient
func NewGreeterClient(enc *nats.EncodedConn, opts ...natsrpc.ClientOption) (*GreeterClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com.byebyebruce.example.pb.async_service.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &GreeterClient{
		c: c,
	}
	return ret, nil
}

// Hello
func (c *GreeterClient) Hello(ctx context.Context, req *pb.HelloRequest, opt ...natsrpc.CallOption) (*pb.HelloReply, error) {
	rep := &pb.HelloReply{}
	err := c.c.Request(ctx, "Hello", req, rep, opt...)
	return rep, err
}

// HelloToAll
func (c *GreeterClient) HelloToAll(notify *pb.HelloRequest) error {
	return c.c.Publish("HelloToAll", notify)
}
