// Code generated by protoc-gen-natsrpc. DO NOT EDIT.
// versions:
// - protoc-gen-natsrpc v0.5.0
// source: header.proto

package header

import (
	context "context"
	fmt "fmt"
	natsrpc "github.com/byebyebruce/natsrpc"
	testdata "github.com/byebyebruce/natsrpc/testdata"
	nats_go "github.com/nats-io/nats.go"
	proto "google.golang.org/protobuf/proto"
)

var _ = new(context.Context)
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = natsrpc.Version
var _ = nats_go.Version

type GreeterNATSRPCServer interface {
	Hello(ctx context.Context, req *testdata.HelloRequest) (*testdata.HelloReply, error)
	HelloPublish(ctx context.Context, req *testdata.HelloRequest)
}

// RegisterGreeterNATSRPCServer register Greeter service
func RegisterGreeterNATSRPCServer(server *natsrpc.Server, s GreeterNATSRPCServer, opts ...natsrpc.ServiceOption) (natsrpc.IService, error) {
	return server.Register("github.com.byebyebruce.natsrpc.example.pb.header.Greeter", s, opts...)
}

type GreeterNATSRPCClient interface {
	Hello(ctx context.Context, req *testdata.HelloRequest, opt ...natsrpc.CallOption) (*testdata.HelloReply, error)
	HelloPublish(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error
}

type _GreeterNATSRPCClient struct {
	c *natsrpc.Client
}

// NewGreeterNATSRPCClient
func NewGreeterNATSRPCClient(enc *nats_go.EncodedConn, opts ...natsrpc.ClientOption) (GreeterNATSRPCClient, error) {
	c, err := natsrpc.NewClient(enc, "github.com.byebyebruce.natsrpc.example.pb.header.Greeter", opts...)
	if err != nil {
		return nil, err
	}
	ret := &_GreeterNATSRPCClient{
		c: c,
	}
	return ret, nil
}
func (c *_GreeterNATSRPCClient) Hello(ctx context.Context, req *testdata.HelloRequest, opt ...natsrpc.CallOption) (*testdata.HelloReply, error) {
	rep := &testdata.HelloReply{}
	err := c.c.Request(ctx, "Hello", req, rep, opt...)
	return rep, err
}
func (c *_GreeterNATSRPCClient) HelloPublish(notify *testdata.HelloRequest, opt ...natsrpc.CallOption) error {
	return c.c.Publish("HelloPublish", notify, opt...)
}
